pipeline {
    agent any
    environment {
        DOCKERHUB_CREDS = credentials('docker-credentials')
    }
    stages {
        stage('Check the repository out') {
            steps {
                checkout scm
            }
        }
    

        stage('Extract Docker Credentials') {
            steps {
                script {
                    // Use the extracted Docker Hub credentials as needed
                    echo "Docker Hub Username: ${DOCKERHUB_CREDS_USR}"
                    echo "Docker Hub Password: ${DOCKERHUB_CREDS_PSW}"
                                                                 sh 'docker build -t esertgmu/hw2 ./SWE645-AEDL-HW2'
                    sh "docker login -u ${DOCKERHUB_CREDS_USR} -p ${DOCKERHUB_CREDS_PSW}"
                    sh 'docker push esertgmu/hw2'
                }
            }
            
        }

        stage('Deploy using the deployment.yaml') {
            steps {
                script {
                    sh 'kubectl apply -f ./kubernetes/deployment.yaml'
                }
            }
        }
    }
}
