pipeline {
    agent any

    stages {
        stage('Check the repository out') {
            steps {
                checkout scm
            }
        }

        stage('Build and Push Docker Image') {
            withCredentials([usernamePassword(credentialsId: 'docker-credentials', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASSWORD')]) {
                steps {
                    script {
                                                                    echo "Docker Hub Username: ${env.DOCKER_USER}"
                        echo "Docker Hub Password: ${env.DOCKER_PASSWORD}"
                        sh 'docker build -t esertgmu/hw2 ./SWE645-AEDL-HW2'
                        sh "docker login -u ${env.DOCKER_USER} -p ${env.DOCKER_PASSWORD}"
                        sh 'docker push esertgmu/hw2'
                    }
                }
            }
        }

        stage('Deploy using the deployment.yaml') {
            steps {
                script {
                    sh 'kubectl apply -f ./kubernetes/deployment.yaml'
                }
            }
        }
    }
}